### ISSUE TITLE
`/leaderboard` doesn't always respond

### ISSUE THREAD

**Issue by dudeofawesome** [Virginity-Bot/virginity-bot#127]
![image](https://user-images.githubusercontent.com/1683595/218030702-866aa931-e7b7-404e-816e-121d73a56ce6.png)

There are no error logs.

**Comment by dudeofawesome** [comment]
Looks like this could be caused by an issue with closing open events

```
Cannot read properties of undefined (reading 'guild') {"context":"ExceptionsHandler","stack":["TypeError: Cannot read properties of undefined (reading 'guild')
    at DatabaseService.closeEvent (/home/vbot/app/src/database/database.service.ts:175:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Track.voiceStateUpdate (/home/vbot/app/src/bot/events/track.ts:72:21)
    at async descriptor.value (/home/vbot/app/node_modules/@mikro-orm/core/decorators/UseRequestContext.js:15:20)
    at async target (/home/vbot/app/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
    at async /home/vbot/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24"]}
```

**Comment by EdgarSaldivar** [comment]
strange it doesnt effect stem2 thought

**Comment by dudeofawesome** [comment]
https://grafana.saldivar.io/explore?orgId=1&left=%7B%22datasource%22%3A%223k4kduAVz%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%223k4kduAVz%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22expr%22%3A%22%7Bapp%3D%5C%22virginity-bot%5C%22%7D+%7C%3D+%60%60%22%2C%22queryType%22%3A%22range%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221676070220000%22%2C%22to%22%3A%221676070300000%22%7D%7D

**Comment by dudeofawesome** [comment]
Could be a race condition with the track event

**Comment by dudeofawesome** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1683595/218293389-ad3d1841-d322-462c-84cc-db8535e718eb.png">

Between these 2 calls, everyone in The Neighborhood left VC

**Comment by dudeofawesome** [comment]
I _think_ we've replaced this behavior with an error message now

https://discord.com/channels/535630284599853076/689074435059089444/1077147895729487872

https://grafana.saldivar.io/explore?orgId=1&left=%7B%22datasource%22%3A%223k4kduAVz%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%223k4kduAVz%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22expr%22%3A%22%7Bapp%3D%5C%22virginity-bot%5C%22%7D+%7C%3D+%60%60%22%2C%22queryType%22%3A%22range%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221676882400000%22%2C%22to%22%3A%221676882580000%22%7D%7D

```
[31m  ERROR[39m [33m[CatchallErrorFilter][39m ValidationError: Trying to persist not discovered entity of type undefined.
    at ValidationError.notDiscoveredEntity (/home/vbot/app/node_modules/@mikro-orm/core/errors.js:50:16)
    at SqlEntityManager.persist (/home/vbot/app/node_modules/@mikro-orm/core/EntityManager.js:888:48)
    at SqlEntityManager.persistAndFlush (/home/vbot/app/node_modules/@mikro-orm/core/EntityManager.js:900:20)
    at SqlEntityRepository.persistAndFlush (/home/vbot/app/node_modules/@mikro-orm/core/entity/EntityRepository.js:21:23)
    at LeaderboardCommand.recalculateScores (/home/vbot/app/src/bot/commands/leaderboard.command.ts:132:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LeaderboardCommand.handler (/home/vbot/app/src/bot/commands/leaderboard.command.ts:80:5)
    at async descriptor.value (/home/vbot/app/node_modules/@mikro-orm/core/decorators/UseRequestContext.js:15:20)
```
