### ISSUE TITLE
Crash on setting role color

### ISSUE THREAD

**Issue by dudeofawesome** [Virginity-Bot/virginity-bot#28]
```ts
await role.setColor(configuration.role.color);
```

```
/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:498
                                throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
          ^
DiscordAPIError[50013]: Missing Permissions
    at SequentialHandler.runRequest (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:498:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.queueRequest (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:198:11)
    at REST.request (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at RoleManager.edit (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/node_modules/discord.js/src/managers/RoleManager.js:209:15)
    at DiscordHelperService.findOrCreateBiggestVirginRole (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/src/bot/discord-helper.service.ts:123:7)
    at UpdatedGuilds.guildJoined (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/src/bot/events/update-guilds.ts:52:5)
    at UpdatedGuilds.descriptor.value (/Users/dudeofawesome/git/EdgarSaldivar/VirginityBot/node_modules/@mikro-orm/core/decorators/UseRequestContext.js:15:20)
```

**Comment by dudeofawesome** [comment]
I think this is just a standard role perms error, which we'll need to handle just by letting it go.

**Comment by EdgarSaldivar** [comment]
letting it go?

**Comment by dudeofawesome** [comment]
like, ignoring the error

**Comment by EdgarSaldivar** [comment]
that means we cant change the color then?

**Comment by dudeofawesome** [comment]
No, we can, it's just that the permissions _could_ be screwed up, which would cause this crash.
